spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.metamodel.model.domain=DEBUG
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.thymeleaf.check-template-location=false
logging.level.org.hibernate.type.descriptor.sql=TRACE
grpc.auth-service-secret=1234
grpc.auth-service-port=8081
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
