stages:
  - test

test-java-app:
  stage: test
  image: gradle:8.12.1-jdk17
  tags:
    - students-buildkit-medium
  script:
    - cd backend/bookservice
    - gradle test --info --tests "*"
  artifacts:
    paths:
      - build/test-results
      - build/reports
    when: always
  cache:
    paths:
      - .gradle/
